from sqlalchemy import Column, Integer, String, Float
from database import Base # Import Base from the main database file

# Define the SQLAlchemy ORM model for the 'products' table
class Product(Base):
    __tablename__ = "products"
    
    # The 'id' column is the primary key and will be auto-generated by the database
    id = Column(Integer, primary_key=True, index=True)
    name= Column(String)
    description= Column(String)
    price= Column(Float)
    quantity= Column(Integer)
